language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer install --dev
  - mkdir -p build/logs
  - chmod +x bin/phpunit
  - chmod +x bin/coveralls
script:
  - bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry bin/coveralls -v
